### ISSUE TITLE
Lower minSdk version

### ISSUE THREAD

**Issue by Lyxnx** [saschpe/Log4K#56]
When you moved to using gradle catalogs in commit https://github.com/saschpe/Log4K/commit/656bb651685a87c7bf440234fde03ef631df30cf, the minSdk was updated to 24 versus the previous 17. Is there any reason for this upgrade? 

Many applications and libraries have a lower minimum version than 24, so although this library still works, it has to be worked around. 21 is usually a good minimum since the Jetpack libraries have a minimum of that nowadays.

**Comment by saschpe** [comment]
Android 7 / Nougat as a basis covers 98% of the current market. API level 10 is now 10 years old. If you still have a substantial customer base there, I could reduce the minSdk for sure.
