### ISSUE TITLE
Support SLF4J version 2 API via `ServiceLoader` mechanism

### ISSUE THREAD

**Issue by sschuberth** [saschpe/Log4K#61]
In a Kotlin/JVM project that has Java dependencies that use the SLF4J 2 API for logging, adding `log4k-slf4j` as a dependency does not make logs from those dependencies appear on the console. I assume this is because `log4k-slf4j` still uses the version 1 API which uses the `org.slf4j.impl.StaticLoggerBinder` mechanism to discover logger implementations. [SLF4J version 2 API](https://www.slf4j.org/faq.html#changesInVersion200) uses the [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) mechanism, though.

So, would it be possible to make `log4k-slf4j` API version 2 compliant?

**Comment by saschpe** [comment]
Hey there. I remain a bit torn on this one. Updating to API version 2 would be the easiest but there is some other software out there using the old SLF4J API. A more graceful approach could be to introduce `log4k-slf4j2` additionally. Gonna have to give it some thought...

**Comment by sschuberth** [comment]
> Updating to API version 2 would be the easiest but there is some other software out there using the old SLF4J API.

Still, I wonder whether updating to API version 2 would "just work": Gradle's version conflict resolution would update any SLF4J dependency to the latest version, and because of

> SLF4J 2.0.0 incorporates an optional [fluent api](https://www.slf4j.org/manual.html#fluent). Otherwise, there are no client facing API changes in 2.0.x.

there should be not problems with users of the old SLF4J API, or?

**Comment by saschpe** [comment]
`org.apache.logging.log4j:log4j-api:2.24.0` or `org.slf4j:slf4j-api:2.0.16`?
